### ISSUE TITLE
Remove loadBeforeVenobox() and jquery.loadBeforeVenobox.js

### ISSUE THREAD

**Issue by ghost** [bertmert/GHSVSThings#23]
JS replaced by PHP in resizerghsvs plugin.

**Comment by ReLater** [comment]
Partially done:

- Removed method parameter `$loadbeforevenobox = 1` in `public static function venobox(` (2 times!!)

- Removed in `public static function venobox(`

```
if ($loadbeforevenobox)
{
self::loadBeforeVenobox();
}
```

- Removed public static function loadBeforeVenobox()

- Moved to folder __HALDE__:
`jquery.loadbeforevenobox-uncompressed.js`
`jquery.loadbeforevenobox.js`

- Removed comment in index.php
