### ISSUE TITLE
PLG_CONTENT_MENUDATEALIASGHSVS is ready. Tell me how to publish it!

### ISSUE THREAD

**Issue by ReLater** [bertmert/GHSVSThings#5]

**Comment by bertmert** [comment]
Thx, Re:Later! Hav tu toenk oever prozederi.

**Comment by bertmert** [comment]
Sorry! I will think about how an where.

**Comment by ghost** [comment]
1) As always our update server and on page /programmierer-schnipsel/joomla/189-plugin-menuetyp-menuealias-alias-wieder-zeitstempel (Already done in relaunch page!)

2) A repository here whenever you have time and if you like the idea.

**Comment by ghost** [comment]
1) Done on production page, too.

**Comment by GHSVS-de** [comment]
2) Done
